version: 2
jobs:
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/Piezoid/homebrew-bio
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          brew --version
          brew remove $(brew list)
          rm -rf /usr/local/Homebrew/Library/Taps/
          brew update-reset
          brew --env
          brew config
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
          repo=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $repo
          cp -a ./ $repo/
      - run:
          no_output_timeout: 30m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-bio --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
            mv brew-test-bot.xml brew-test-bot-macos.xml
workflows:
  version: 2
  test-bot:
    jobs:
      - build-macos

